### ISSUE TITLE
Add example for nodejs connection

### ISSUE THREAD

**Issue by bhoudu** [aws-samples/amazon-keyspaces-examples#15]
The plugin https://github.com/aws/aws-sigv4-auth-cassandra-nodejs-driver-plugin exists and works well, would it be possible to add in this repo an example of use?

**Comment by bhouse99** [comment]
Thanks so much for the suggestion!  We will consider that for our roadmap.

**Comment by bhouse99** [comment]
As we have just recently added a nodejs example, going to close this particular issue.
