### ISSUE TITLE
Missing the CQL command on the "export to S3" readme file 

### ISSUE THREAD

**Issue by murilocn-aws** [aws-samples/amazon-keyspaces-examples#32]
In [scala/datastax-v4/aws-glue/export-to-s3](https://github.com/aws-samples/amazon-keyspaces-examples/tree/main/scala/datastax-v4/aws-glue/export-to-s3) there's a missing CQL command on
[README.md](https://github.com/aws-samples/amazon-keyspaces-examples/blob/main/scala/datastax-v4/aws-glue/export-to-s3/README.md)

# Update the partitioner for your account
In Apache Cassandra, partitioners control which nodes data is stored on in the cluster. Partitioners create a numeric token using a hashed value of the partition key. Cassandra uses this token to distribute data across nodes. To use Apache Spark or AWS glue you will need to update the partitioner. You can execute this CQL command from the Amazon Keyspaces console [CQL editor](https://console.aws.amazon.com/keyspaces/home#cql-editor)

There's no command;

**Comment by michaelraney** [comment]
Updated, Thank you!
